apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: blog-app-s
provisioner: kubernetes.io/aws-ebs
reclaimPolicy: Retain
allowVolumeExpansion: true
parameters:
  type: gp2
mountOptions:
- debug
volumeBindingMode: Immediate

